server:
  port: 9000
  servlet:
    context-path: /ecom

logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.ecom.prodsearch: DEBUG

spring:
  application:
    name: ecom
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
