server:
  port: 8000

logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.ecom.prodsearch: DEBUG

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
