DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    PRODUCT_TYPE VARCHAR2(255) NOT NULL,
    BRAND VARCHAR2(50),
    PRICE INTEGER NOT NULL,
    SIZE VARCHAR2(10),
    QUANTITY INTEGER NOT NULL,
    CREATED_DATE DATE NOT NULL,
    LAST_MODIFIED_DATE date,
    PRIMARY KEY(ID)
);

CREATE sequence PRODUCT_ID_SEQ
minvalue 1
maxvalue 999999999
start with 1
increment by 100
cache 100;

commit ;